
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author O_TEEB
 */
public class report extends javax.swing.JInternalFrame {

    public Connection getConnection(){
        Connection c = null;
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/projectwarehouse","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ไม่สามารถชื่อมต่อได้\n"+ex);
        }
        return c;
    }
    public report() {
        initComponents();
        
        Connection Conn = this.getConnection();
        Statement SQLstmt;
        
        try {
            SQLstmt = Conn.createStatement();
            String sqli = "SELECT * FROM report INNER JOIN products ON report.products_id=products.products_id ORDER BY report.report_id DESC";
            ResultSet rsi = SQLstmt.executeQuery(sqli);
            
            DefaultListModel <String> model = new DefaultListModel<>();
                model.addElement("-----------------------------------------------------------------------------------------------\n");
                model.addElement("                                              รายงาน\n");
                model.addElement("-----------------------------------------------------------------------------------------------\n");
                model.addElement("ลำดับที่       ชื่อสินค้า       ราคาต่อหน่วย       หน่วยนับ       จำนวนที่จ่ายไป     วัน/เดือน/ปีที่จ่ายไป");
                while(rsi.next()){
                model.addElement(rsi.getString("report_id")+
                                              "                    "
                                +rsi.getString("products_name")+
                                              "                  "
                                +rsi.getString("products_price")+
                                              "                          "
                                +rsi.getString("products_reckon")+
                                              "                   "
                                +rsi.getString("number")+
                                              "                     "
                                +rsi.getString("date"));
                }
                jList2.setModel(model);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"ไม่พบข้อมูล"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(700, 680));

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 48)); // NOI18N
        jLabel1.setText("----------Report----------");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addGap(178, 178, 178))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
