
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author O_TEEB
 */
public class sell extends javax.swing.JInternalFrame {

    /**
     * Creates new form sell
     */
    
     public Connection getConnection(){
        Connection c = null;
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost/projectwarehouse","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ไม่สามารถชื่อมต่อได้\n"+ex);
        }
        return c;
    }
    public sell() {
        initComponents();
      
        Connection Conn = this.getConnection();
        Statement SQLstmt;
        
        try {
            SQLstmt = Conn.createStatement();
            String sqli = "select * from products";
            ResultSet rsi = SQLstmt.executeQuery(sqli);
            
            DefaultListModel <String> model = new DefaultListModel<>();
                model.addElement("---------------------------------------------------------------------------------------\n");
                model.addElement("                                              จำนวนสินค้าคงคลัง\n");
                model.addElement("---------------------------------------------------------------------------------------\n");
                model.addElement("รหัสสินค้า           ชื่อสินค้า           ราคาต่อหน่วย           หน่วยนับ           จำนวนคงคลัง    ");
                while(rsi.next()){
                model.addElement(rsi.getString("products_id")+
                                              "                      "
                                +rsi.getString("products_name")+
                                              "                    "
                                +rsi.getString("products_price")+
                                              "                            "
                                +rsi.getString("products_reckon")+
                                              "                     "
                                +rsi.getString("products_number"));
                }
                jList2.setModel(model);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"ไม่พบข้อมูล"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1041, 520));

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 48)); // NOI18N
        jLabel1.setText("-------------Cut Stock--------------");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel3.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel3.setText("ชื่อสินค้า :");

        jLabel4.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel4.setText("ราคาต่อหน่วย :");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel6.setText("จำนวนคงคลัง :");

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jButton1.setText("ตกลง");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel2.setText("รหัสสินค้า :");

        jButton4.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jButton4.setText("ค้นหา");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel7.setText("จำนวนที่จ่ายออก :");

        jLabel8.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel8.setText("วัน/เดือน/ปี ที่จ่ายออก :");

        jLabel9.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*รูปแบบการป้อน = วัน-เดือน-ปี");

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel10.setText("วัน");

        jLabel11.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel11.setText("เดือน");

        jLabel12.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel12.setText("ปี");

        jLabel13.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel13.setText("-");

        jLabel14.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel14.setText("-");

        jLabel15.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("เช่น 5-09-2017");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel11)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel12)
                                .addGap(101, 101, 101))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jTextField2))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel9))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(2, 2, 2)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if((jTextField1.getText().isEmpty())||
            (jTextField2.getText().isEmpty())||
            (jTextField4.getText().isEmpty())||
            (jTextField5.getText().isEmpty())||
            (jTextField6.getText().isEmpty())
        ){
            JOptionPane.showMessageDialog(this, "กรุณาป้อนค่า");
            return;
        }
        
        if((Integer.parseInt(jTextField4.getText()))>(Integer.parseInt(jTextField5.getText()))){
            JOptionPane.showMessageDialog(this, "สินค้าไม่พอที่จะจ่ายออก!!!");
            return;
        }
        
        if(JOptionPane.showConfirmDialog(this, "ต้องการตัด Stock หรือไม่?")!=0){
            return;
        }
        
        int i = 0;
        i = (Integer.parseInt(jTextField5.getText()))-(Integer.parseInt(jTextField4.getText()));
        Connection Conn = this.getConnection();
        Statement SQLstmt;
        
        try {
            SQLstmt = Conn.createStatement();
            String sql = "update products set products_number='"+i+"'";
            sql += " where products_id='"+jTextField1.getText()+"'";

            SQLstmt.executeUpdate(sql);

            sql = "select * from products where products_id = '"+jTextField1.getText()+"'";
            ResultSet rs = SQLstmt.executeQuery(sql);
            DefaultListModel <String> model = new DefaultListModel<>();
            model.addElement("---------------------------------------------------------------------------------------\n");
            model.addElement("                                              Manaqe Item\n");
            model.addElement("---------------------------------------------------------------------------------------\n");
            model.addElement("รหัสสินค้า           ชื่อสินค้า           ราคาต่อหน่วย           หน่วยนับ           จำนวนคงคลัง    ");
            while(rs.next()){
                model.addElement(rs.getString("products_id")+
                                              "                      "
                                +rs.getString("products_name")+
                                              "                    "
                                +rs.getString("products_price")+
                                              "                            "
                                +rs.getString("products_reckon")+
                                              "                     "
                                +rs.getString("products_number"));
                jTextField5.setText(rs.getString("products_number"));              
            }
            jList2.setModel(model);
            JOptionPane.showMessageDialog(this, "ตัด Stock สำเร็จ");
            
            String j = "'"+jTextField8.getText();
            j += "-";
            j += jTextField7.getText();
            j += "-";
            j += jTextField6.getText()+"'";
            
            String sqli = "insert into report (report_id,products_id,date,number) values ";
            sqli += "(null,";
            sqli += "'"+jTextField1.getText()+"',";
            sqli += j+",";
            sqli += "'"+jTextField4.getText()+"')";
            SQLstmt.executeUpdate(sqli);
            jTextField4.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "เกิดข้อผิดพลาด"+ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()!=KeyEvent.VK_ENTER){
            return;
        }
        if((jTextField1.getText().isEmpty())){
            JOptionPane.showMessageDialog(this, "กรุณาป้อนค่า");
            return;
        }
        Connection Conn = this.getConnection();
        Statement SQLstmt;
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField5.setEnabled(false);
        try {
            SQLstmt = Conn.createStatement();
            String sql = "select * from products where products_id = '"+jTextField1.getText()+"'";
            ResultSet rs = SQLstmt.executeQuery(sql);
            rs.last();

            if(rs.getRow()==0){
                JOptionPane.showMessageDialog(this,"ไม่พบข้อมูล");
                return;
            }else{
                jTextField2.setText(rs.getString("products_name"));
                jTextField3.setText(rs.getString("products_price"));
                jTextField5.setText(rs.getString("products_number"));

                DefaultListModel <String> model = new DefaultListModel<>();
                model.addElement("---------------------------------------------------------------------------------------\n");
                model.addElement("                                              Manaqe Item\n");
                model.addElement("---------------------------------------------------------------------------------------\n");
                model.addElement("รหัสสินค้า           ชื่อสินค้า           ราคาต่อหน่วย           หน่วยนับ           จำนวนคงคลัง    ");
                model.addElement(rs.getString("products_id")+
                    "                      "
                    +rs.getString("products_name")+
                    "                    "
                    +rs.getString("products_price")+
                    "                            "
                    +rs.getString("products_reckon")+
                    "                     "
                    +rs.getString("products_number"));
                jList2.setModel(model);
                Conn.close();
                jButton1.setEnabled(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ผิดพลาด\n"+ex);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if((jTextField1.getText().isEmpty())){
            JOptionPane.showMessageDialog(this, "กรุณาป้อนค่า");
            return;
        }
        Connection Conn = this.getConnection();
        Statement SQLstmt;
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField5.setEnabled(false);
        try {
            SQLstmt = Conn.createStatement();
            String sql = "select * from products where products_id = '"+jTextField1.getText()+"'";
            ResultSet rs = SQLstmt.executeQuery(sql);
            rs.last();
            if(rs.getRow()==0){
                JOptionPane.showMessageDialog(this,"ไม่พบข้อมูล");
                return;
            }else{
                jTextField2.setText(rs.getString("products_name"));
                jTextField3.setText(rs.getString("products_price"));
                jTextField5.setText(rs.getString("products_number"));

                DefaultListModel <String> model = new DefaultListModel<>();
                model.addElement("---------------------------------------------------------------------------------------\n");
                model.addElement("                                              Manaqe Item\n");
                model.addElement("---------------------------------------------------------------------------------------\n");
                model.addElement("รหัสสินค้า           ชื่อสินค้า           ราคาต่อหน่วย           หน่วยนับ           จำนวนคงคลัง    ");
                model.addElement(rs.getString("products_id")+
                    "                      "
                    +rs.getString("products_name")+
                    "                    "
                    +rs.getString("products_price")+
                    "                            "
                    +rs.getString("products_reckon")+
                    "                     "
                    +rs.getString("products_number"));

                jList2.setModel(model);
                Conn.close();
                jButton1.setEnabled(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ผิดพลาด\n"+ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTextField4KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
